---
  - name: "print environment"
    shell: env

  - name: "copy backend dist"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "copy node_modules"
    become: yes
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/uda_app
      recursive: true

  - name: "pm2 delete all"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "pm2 start -f ./main.js"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/uda_app/dist
    environment:
     ENVIRONMENT: production
     NODE_ENV: production
     TYPEORM_CONNECTION: postgres
     TYPEORM_MIGRATIONS_DIR: ~/src/migrations
     TYPEORM_MIGRATIONS: ~/src/migrations/*.ts
     TYPEORM_ENTITIES: ~/src/modules/domain/**/*.entity.ts
     TYPEORM_HOST: database-1.cdhvplicvn2r.us-east-1.rds.amazonaws.com
     TYPEORM_PORT: 5432
     TYPEORM_USERNAME: postgres
     TYPEORM_PASSWORD: mypassword
     TYPEORM_DATABASE: postgres